/**:
  ros__parameters:

    # code run parameters
    develop: True
    stopwatch: False

    # settings
    thresh_HDwebCam: 180
    thresh_ZED: 100
    resolution_ZED: 376 # 376 or 1242 [pixel]
    horizon_dist: 1 # 1 or 2 [m]

    # colors
    color_white: [255, 255, 255]
    color_red: [0, 0, 255]
    color_green: [0, 255, 0]
    color_blue: [255, 0, 0]
    color_purple: [155, 25, 220]
    color_gray: [150, 150, 150]



